### ISSUE TITLE
Fails to create CSV

### ISSUE THREAD

**Issue by GregoryConrad** [uridvir/wpi_bannerweb_csv#6]
Here's the error from the console:

```
Uncaught TypeError: Cannot read property 'trim' of undefined
    at new Course (course.js:41)
    at HTMLInputElement.window.exportAction (content.js:32)
Course @ course.js:41
window.exportAction @ content.js:32
```

This is on Chrome 76.0.3809.100 (Official Build) (64-bit) for Windows

Let me know if you need anything else

**Comment by uridvir** [comment]
Interesting. It seems like that error would only happen when the time range for a course isn't formatted with a hyphen (usually something like "9:00am-9:50am"). Which version of the extension are you using, and are you trying to export from WPI BannerWeb?

**Comment by GregoryConrad** [comment]
I was using WPI BannerWeb and was using the latest version of the extension on the webstore at the time of that posting. I'll go check BannerWeb and see how the times are formatted.

**Comment by GregoryConrad** [comment]
Looks like my last course (the varsity swim team) has a time of TBA (with no hyphen). That might be causing the issue.

It may be worth skipping the current course if its scheduled time does not contain a hyphen.

**Comment by uridvir** [comment]
I just tested this by using inspect element to reproduce the behavior (I pushed the commit before I realized I could test this myself). I think the bug's gone.

**Comment by GregoryConrad** [comment]
The code on the develop branch worked great for me. Thanks for fixing!
